import { StyleSheet, Dimensions } from 'react-native';

const designpattern = StyleSheet.create({
/**Page layout */
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    containerleft: {
        flex: 1,
      },
/**Text */
    title: {
      fontSize: 20,
      fontWeight: 'bold',
    },
    titlesmall: {
        fontSize: 17,
        fontWeight: 'bold',
      },
    normalpassive: {
        fontSize: 15,
        fontWeight: 'normal',
        color: "grey",
      },
    normal: {
        fontSize: 15,
        fontWeight: 'normal',
      },
    normaltextprimebutton: {
        fontSize: 15,
        fontWeight: 'bold',
        color: "white",
    },
    titletextprimebutton: {
        fontSize: 20,
        fontWeight: 'bold',
        color: "white",
    },
    offertitling: {
        position: "relative",
        color: "black",
        marginVertical: 5,
        backgroundColor: 'rgba(0,0,0,0)',
    },
    logo: {
        fontSize: 80,
        fontWeight: 'normal',
        color: "white",
        textShadowColor: "#8f7e7e",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 6,
        letterSpacing: 8,
    },
/**Separators */
    separator: {
        backgroundColor: 'rgba(0,0,0,0)',
        marginVertical: 30,
        height: 1,
        width: '80%',
    },
    separatorsmall: {
        backgroundColor: 'rgba(0,0,0,0)',
        marginVertical: 10,
        height: 0,
    },
    separatorofferdisplay: {
        backgroundColor: 'rgba(0,0,0,0)',
        marginTop: 10,
        height: 0,
    },
    separatorhorizontallist: {
        backgroundColor: 'rgba(0,0,0,0)',
        marginVertical: 15,
        height: 0,
    },
    separatorhorizontal: {
        backgroundColor: 'rgba(0,0,0,0)',
        width: 10,
    },
/**placing */
    center: {
        alignItems: 'center',
        justifyContent: "center",
        backgroundColor: 'rgba(0,0,0,0)',
    },
    deletesavedservice: {
        alignItems: 'center',
        marginHorizontal: 15,
        justifyContent: "center",
        backgroundColor: 'rgba(0,0,0,0)',
    },
    centerleft: {
        justifyContent: "center",
        backgroundColor: 'rgba(0,0,0,0)',
    },
    left: {
        marginLeft: 10,
    },
    alignitems: {
        flexDirection: "row",
        backgroundColor: 'rgba(0,0,0,0)',
    },
    actionsugestor: {
        borderRadius: 20,
        position: "absolute",
        bottom: 10,
        left: "10%",
        right: "10%",
        backgroundColor: "blue",
        paddingVertical: 10,
    },
/**buttons */
    roundbutton: {
        height: 60,
        width: 60,
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
        borderRadius: 40,
        margin: 5,
        backgroundColor: "white",
        justifyContent: "center",
        alignItems: 'center',
        alignSelf: "center",
    },
    buttonprimary: {
        margin: 5,
        height: 40,
        alignSelf: 'flex-start',
        paddingHorizontal: 25,
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
        borderRadius: 20,
        backgroundColor: "orange",
        justifyContent: "center",
    },
    buttonprimaryicon: {
        margin: 5,
        height: 40,
        width: 50,
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
        borderRadius: 20,
        backgroundColor: "orange",
        justifyContent: "center",
    },
    buttondefaulticon: {
        margin: 5,
        height: 40,
        width: 50,
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
        borderRadius: 20,
        backgroundColor: "white",
        justifyContent: "center",
    },
    buttonsecondary: {
        height: 40,
        margin: 5,
        alignSelf: 'flex-start',
        paddingHorizontal: 15,
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "orange",
        backgroundColor: "white",
        justifyContent: "center",
    },
    buttondefault: {
        height: 40,
        margin: 5,
        alignSelf: 'flex-start',
        paddingHorizontal: 15,
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 1, height: 2 },
        borderRadius: 20,
        backgroundColor: "white",
        justifyContent: "center",
    },
    buttoninformative: {
        height: 30,
        marginVertical: 5,
        marginRight: 5,
        alignSelf: 'flex-start',
        justifyContent: "center",
        paddingHorizontal: 10,
        borderRadius: 20,
        backgroundColor: "#fce9ca",
    },
    buttonactionrequest: {
        height: 30,
        marginVertical: 5,
        marginRight: 5,
        alignSelf: 'flex-start',
        justifyContent: "center",
        paddingHorizontal: 10,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "orange",
        backgroundColor: "#fce9ca",
    },
    primary: {
        height: 30,
        marginVertical: 5,
        marginRight: 5,
        alignSelf: 'flex-start',
        justifyContent: "center",
        paddingHorizontal: 10,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "orange",
        backgroundColor: "orange",
    },
    secondary: {
        height: 30,
        marginVertical: 5,
        marginRight: 5,
        alignSelf: 'flex-start',
        justifyContent: "center",
        paddingHorizontal: 10,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "orange",
        backgroundColor: "white",
    },
/**Inputs */
    inputactionrequired: {
        height: 40,
        margin: 5,
        alignSelf: 'flex-start',
        paddingHorizontal: 15,
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "orange",
        backgroundColor: "white",
        justifyContent: "center",
    },
    inputstandard: {
        height: 40,
        margin: 5,
        alignSelf: 'flex-start',
        paddingHorizontal: 15,
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
        borderRadius: 20,
        backgroundColor: "white",
        justifyContent: "center",
    },
/**Images */
    image: {
        flex: 1,
        justifyContent: "center"
    },
/**Elements */
    /**Offernavigation */
    offernavigationbackground: {
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        position: "absolute",
        bottom: 10,
        paddingVertical: 0,
        paddingHorizontal: 0,
        borderRadius: 40,
        flexDirection: "row",
    },
    scrollviewofferoptions: {
        backgroundColor: 'rgba(0,0,0,0)',
        borderRadius: 40,
    },
    offernavigationlength: {
        borderRadius: 20,
        width: 170,
        backgroundColor: 'rgba(0,0,0,0)',
    },
    /**Backgrounds */
    offerinfobackground: {
        width: 350,
        height: 500,
        backgroundColor: "#fcf6ed",
        borderRadius: 20,
        padding: 20,
    },
    defaultbackground: {
        backgroundColor: "#fcf6ed",
        borderRadius: 20,
        paddingHorizontal: 20,
        paddingVertical: 15,
        marginHorizontal: 20,
        marginVertical: 10,
    },
    offerbackground: {
        backgroundColor: "white",
        borderRadius: 20,
        paddingHorizontal: 0,
        paddingTop: 30,
        paddingBottom: 10,
        marginVertical: 10,
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
    },
    /**Offercontainer */
    offercontainer: {
        alignItems: "center",
        marginHorizontal: 10,
        borderRadius: 0,
        marginBottom: 80,
        height: 800,
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
    },

    picturemaxheight: {
        width: "100%",
    },
    picturesizing: {
        resizeMode: "contain",
        width: Dimensions.get('window').width,
        height: 400,
    },
    servicecontainer: {
        width: "100%",
        backgroundColor: 'rgba(0,0,0,0)',
    },


    visuals: {
        backgroundColor: 'lightgrey',
        width: 100,
        height: 100,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 10,
        marginVertical: 5,
    },
    /**no groups */
    savedservicelist: {
        marginLeft: 10,
    },
    searchinfeed: {
        position: "absolute",
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderBottomRightRadius: 20,
        borderColor: "grey",
        top: 0,
        fontSize: 15,
        fontWeight: 'normal',
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "rgba(255,255,255,0.8)",
        shadowOffset: { width: 0, height: 2 },
    },
    serveinviter: {
        position: "absolute",
        paddingHorizontal: 50,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: 'orange',
        borderWidth: 0,
        alignSelf: "center",
        bottom: 10,
        shadowColor: "#000",
        shadowOpacity: 0.6,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 2 },
    },
});
  export {designpattern}
