import { StyleSheet } from 'react-native';
const designpattern = StyleSheet.create({
/**Page layout */
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
/**Text */
    title: {
      fontSize: 20,
      fontWeight: 'bold',
    },
    normal: {
        fontSize: 15,
        fontWeight: 'normal',
      },
    normaltextprimebutton: {
        fontSize: 15,
        fontWeight: 'bold',
        color: "white",
    },
    titletextprimebutton: {
        fontSize: 20,
        fontWeight: 'bold',
        color: "white",
    },
    logo: {
        fontSize: 80,
        fontWeight: 'normal',
        color: "white",
        textShadowColor: "#8f7e7e",
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 6,
        letterSpacing: 8,
    },
/**Separators */
    separator: {
        backgroundColor: 'rgba(0,0,0,0)',
        marginVertical: 30,
        height: 1,
        width: '80%',
    },
    separatorsmall: {
        backgroundColor: 'rgba(0,0,0,0)',
        marginVertical: 10,
        height: 0,
    },
    separatorhorizontal: {
        backgroundColor: 'rgba(0,0,0,0)',
        width: 10,
    },
/**placing */
    center: {
        alignItems: 'center',
        justifyContent: "center",
    },
    left: {
        marginLeft: 10,
    },
    alignitems: {
        flexDirection: "row",
    },
/**buttons */
    buttonprimary: {
        height: 40,
        paddingHorizontal: 15,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: 2 },
        borderRadius: 20,
        backgroundColor: "orange",
        justifyContent: "center",
    },



    
    floatingprimebottom: {
        borderRadius: 20,
        position: "absolute",
        bottom: 10,
        left: "10%",
        right: "10%",
        backgroundColor: "orange",
        paddingVertical: 10,
        alignItems: 'center',
    },
    appButtonprime: {
        borderRadius: 20,
        marginLeft: 10,
        marginVertical: 5,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "orange",
        shadowOffset: { width: 0, height: 2 },
    },
    appButtondefault: {
        alignSelf: 'flex-start',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 20,
        marginRight: 10,
        marginVertical: 5,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "white",
        shadowOffset: { width: 0, height: 2 },
    },
    appButtondefault2: {
        paddingHorizontal: 15,
        paddingVertical: 5,
        borderRadius: 20,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "white",
        shadowOffset: { width: 0, height: 2 },
    },
    appButtonfeedback: {
        fontSize: 15,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 20,
        marginLeft: 10,
        marginVertical: 5,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "white",
        shadowOffset: { width: 0, height: 2 },
    },
    appButtoncall: {
        alignSelf: 'flex-start',
        paddingHorizontal: 15,
        paddingVertical: 5,
        marginVertical: 10,
        marginHorizontal: 10,
        borderRadius: 20,
        backgroundColor: "orange",
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: 2 },
    },
    appButtoncall1: {
        paddingHorizontal: 15,
        paddingVertical: 5,
        marginVertical: 0,
        borderRadius: 20,
        backgroundColor: "orange",
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: 2 },
    },
    appButtoncalloffline: {
        alignSelf: 'flex-start',
        paddingHorizontal: 15,
        paddingVertical: 5,
        marginVertical: 10,
        marginHorizontal: 10,
        borderRadius: 20,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "white",
        shadowOffset: { width: 0, height: 2 },
    },
    appButtonlink: {
        fontSize: 15,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 20,
        marginLeft: 10,
        marginVertical: 5,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "white",
        shadowOffset: { width: 0, height: 2 },
    },
/**Inputs */
    input: {
        marginLeft: 10,
        marginVertical: 5,
        paddingVertical: 10,
        borderWidth: 2,
        paddingHorizontal: 15,
        borderRadius: 20,
        borderColor: "orange",
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "white",
        shadowOffset: { width: 0, height: 2 },
    },
    input2: {
        marginLeft: 10,
        marginVertical: 5,
        paddingVertical: 10,
        borderWidth: 2,
        paddingHorizontal: 15,
        borderRadius: 20,
        borderColor: "orange",
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "white",
        shadowOffset: { width: 0, height: 2 },
    },
    input1: {
        height: 40,
        margin: 12,
        borderWidth: 1,
        padding: 10,
        borderRadius: 20,
    },
    floatbuttonsearch: {
        borderRadius: 20,
        position: "absolute",
        left: 10,
        top: 10,
        backgroundColor: "white",
        paddingHorizontal: 20,
        paddingVertical: 10,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: 2 },
    },
/**Images */
    image: {
        flex: 1,
        justifyContent: "center"
    },
/**Elements */
    /**Offernavigation */
    offernavigationbackground: {
        backgroundColor: 'rgba(0,0,0,2)',
        position: "absolute",
        bottom: 10,
        paddingVertical: 5,
        paddingHorizontal: 5,
        borderRadius: 40,
        flexDirection: "row",
        marginLeft: 10,
        marginRight: 10,
    },
    scrollviewofferoptions: {
        backgroundColor: 'rgba(0,0,0,0)',
        borderRadius: 20,
    },
    offernavigationlength: {
        borderRadius: 20,
        width: 150,
        backgroundColor: 'rgba(0,0,0,0)',
    },
    /**Offercontainer */
    offercontainer: {
        backgroundColor: "lightgrey",
        marginHorizontal: 10,
        height: 550,
        borderRadius: 20,
        marginBottom: 15,
        shadowColor: "#000",
        shadowOpacity: 0.40,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: 2 },
    },
    visuals: {
        borderRadius: 20,
        backgroundColor: 'lightgrey',
        width: 130,
        height: 180,
        alignItems: 'center',
        alignSelf: 'flex-start',
        justifyContent: 'center',
        marginLeft: 10,
        marginVertical: 5,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: 2 },
    },
    /**no groups */
    uploadfield: {
        borderRadius: 20,
        borderWidth: 2,
        borderColor:'orange',
        width: 130,
        height: 180,
        alignItems: 'center',
        alignSelf: 'flex-start',
        justifyContent: 'center',
        marginLeft: 10,
        marginVertical: 5,
        shadowColor: "#000",
        shadowOpacity: 0.20,
        shadowRadius: 3,
        backgroundColor: "white",
        shadowOffset: { width: 0, height: 2 },
    },
    savedservicelist: {
        marginLeft: 10,
    },
});
  export {designpattern}
